"""
    Otoroshi Admin API

    Admin API of the Otoroshi reverse proxy  # noqa: E501

    The version of the OpenAPI document: 1.5.0-alpha.14
    Contact: oss@maif.fr
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.otoroshi_models_algo_settings import OtoroshiModelsAlgoSettings
from openapi_client.model.otoroshi_models_entity_location import OtoroshiModelsEntityLocation
from openapi_client.model.otoroshi_models_global_jwt_verifier import OtoroshiModelsGlobalJwtVerifier
from openapi_client.model.otoroshi_models_jwt_token_location import OtoroshiModelsJwtTokenLocation
from openapi_client.model.otoroshi_models_local_jwt_verifier import OtoroshiModelsLocalJwtVerifier
from openapi_client.model.otoroshi_models_ref_jwt_verifier import OtoroshiModelsRefJwtVerifier
from openapi_client.model.otoroshi_models_verifier_strategy import OtoroshiModelsVerifierStrategy
globals()['OtoroshiModelsAlgoSettings'] = OtoroshiModelsAlgoSettings
globals()['OtoroshiModelsEntityLocation'] = OtoroshiModelsEntityLocation
globals()['OtoroshiModelsGlobalJwtVerifier'] = OtoroshiModelsGlobalJwtVerifier
globals()['OtoroshiModelsJwtTokenLocation'] = OtoroshiModelsJwtTokenLocation
globals()['OtoroshiModelsLocalJwtVerifier'] = OtoroshiModelsLocalJwtVerifier
globals()['OtoroshiModelsRefJwtVerifier'] = OtoroshiModelsRefJwtVerifier
globals()['OtoroshiModelsVerifierStrategy'] = OtoroshiModelsVerifierStrategy
from openapi_client.model.otoroshi_models_jwt_verifier import OtoroshiModelsJwtVerifier


class TestOtoroshiModelsJwtVerifier(unittest.TestCase):
    """OtoroshiModelsJwtVerifier unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOtoroshiModelsJwtVerifier(self):
        """Test OtoroshiModelsJwtVerifier"""
        # FIXME: construct object with mandatory attributes with example values
        # model = OtoroshiModelsJwtVerifier()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
