"""
    Otoroshi Admin API

    Admin API of the Otoroshi reverse proxy  # noqa: E501

    The version of the OpenAPI document: 1.5.0-alpha.14
    Contact: oss@maif.fr
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.otoroshi_ssl_pki_models_gen_cert_response import OtoroshiSslPkiModelsGenCertResponse


class TestOtoroshiSslPkiModelsGenCertResponse(unittest.TestCase):
    """OtoroshiSslPkiModelsGenCertResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOtoroshiSslPkiModelsGenCertResponse(self):
        """Test OtoroshiSslPkiModelsGenCertResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = OtoroshiSslPkiModelsGenCertResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
