"""
    Otoroshi Admin API

    Admin API of the Otoroshi reverse proxy  # noqa: E501

    The version of the OpenAPI document: 1.5.0-alpha.14
    Contact: oss@maif.fr
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.otoroshi_models_api_key_rotation import OtoroshiModelsApiKeyRotation
from openapi_client.model.otoroshi_models_entity_identifier import OtoroshiModelsEntityIdentifier
from openapi_client.model.otoroshi_models_entity_location import OtoroshiModelsEntityLocation
from openapi_client.model.otoroshi_models_restrictions import OtoroshiModelsRestrictions
globals()['OtoroshiModelsApiKeyRotation'] = OtoroshiModelsApiKeyRotation
globals()['OtoroshiModelsEntityIdentifier'] = OtoroshiModelsEntityIdentifier
globals()['OtoroshiModelsEntityLocation'] = OtoroshiModelsEntityLocation
globals()['OtoroshiModelsRestrictions'] = OtoroshiModelsRestrictions
from openapi_client.model.otoroshi_models_api_key import OtoroshiModelsApiKey


class TestOtoroshiModelsApiKey(unittest.TestCase):
    """OtoroshiModelsApiKey unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOtoroshiModelsApiKey(self):
        """Test OtoroshiModelsApiKey"""
        # FIXME: construct object with mandatory attributes with example values
        # model = OtoroshiModelsApiKey()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
