"""
    Otoroshi Admin API

    Admin API of the Otoroshi reverse proxy  # noqa: E501

    The version of the OpenAPI document: 1.5.0-alpha.14
    Contact: oss@maif.fr
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from openapi_client.api.lines_api import LinesApi  # noqa: E501


class TestLinesApi(unittest.TestCase):
    """LinesApi unit test stubs"""

    def setUp(self):
        self.api = LinesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_otoroshi_controllers_adminapi_services_controller_all_lines(self):
        """Test case for otoroshi_controllers_adminapi_services_controller_all_lines

        Get all lines of work (prod, preprod, etc)  # noqa: E501
        """
        pass

    def test_otoroshi_controllers_adminapi_services_controller_services_for_a_line(self):
        """Test case for otoroshi_controllers_adminapi_services_controller_services_for_a_line

        Get all service for a line of work  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
