"""
    Otoroshi Admin API

    Admin API of the Otoroshi reverse proxy  # noqa: E501

    The version of the OpenAPI document: 1.5.0-alpha.14
    Contact: oss@maif.fr
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.otoroshi_models_team_access import OtoroshiModelsTeamAccess
from openapi_client.model.otoroshi_models_tenant_access import OtoroshiModelsTenantAccess
globals()['OtoroshiModelsTeamAccess'] = OtoroshiModelsTeamAccess
globals()['OtoroshiModelsTenantAccess'] = OtoroshiModelsTenantAccess
from openapi_client.model.otoroshi_models_user_right import OtoroshiModelsUserRight


class TestOtoroshiModelsUserRight(unittest.TestCase):
    """OtoroshiModelsUserRight unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOtoroshiModelsUserRight(self):
        """Test OtoroshiModelsUserRight"""
        # FIXME: construct object with mandatory attributes with example values
        # model = OtoroshiModelsUserRight()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
