"""
    Otoroshi Admin API

    Admin API of the Otoroshi reverse proxy  # noqa: E501

    The version of the OpenAPI document: 1.5.0-alpha.14
    Contact: oss@maif.fr
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.otoroshi_auth_session_cookie_values import OtoroshiAuthSessionCookieValues
from openapi_client.model.otoroshi_models_entity_location import OtoroshiModelsEntityLocation
from openapi_client.model.otoroshi_models_user_rights import OtoroshiModelsUserRights
from openapi_client.model.otoroshi_utils_http_mtls_config import OtoroshiUtilsHttpMtlsConfig
globals()['OtoroshiAuthSessionCookieValues'] = OtoroshiAuthSessionCookieValues
globals()['OtoroshiModelsEntityLocation'] = OtoroshiModelsEntityLocation
globals()['OtoroshiModelsUserRights'] = OtoroshiModelsUserRights
globals()['OtoroshiUtilsHttpMtlsConfig'] = OtoroshiUtilsHttpMtlsConfig
from openapi_client.model.otoroshi_auth_generic_oauth2_module_config import OtoroshiAuthGenericOauth2ModuleConfig


class TestOtoroshiAuthGenericOauth2ModuleConfig(unittest.TestCase):
    """OtoroshiAuthGenericOauth2ModuleConfig unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOtoroshiAuthGenericOauth2ModuleConfig(self):
        """Test OtoroshiAuthGenericOauth2ModuleConfig"""
        # FIXME: construct object with mandatory attributes with example values
        # model = OtoroshiAuthGenericOauth2ModuleConfig()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
