"""
    Otoroshi Admin API

    Admin API of the Otoroshi reverse proxy  # noqa: E501

    The version of the OpenAPI document: 1.5.0-alpha.14
    Contact: oss@maif.fr
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.otoroshi_models_entity_location import OtoroshiModelsEntityLocation
from openapi_client.model.otoroshi_models_otoroshi_admin_type import OtoroshiModelsOtoroshiAdminType
from openapi_client.model.otoroshi_models_user_rights import OtoroshiModelsUserRights
globals()['OtoroshiModelsEntityLocation'] = OtoroshiModelsEntityLocation
globals()['OtoroshiModelsOtoroshiAdminType'] = OtoroshiModelsOtoroshiAdminType
globals()['OtoroshiModelsUserRights'] = OtoroshiModelsUserRights
from openapi_client.model.otoroshi_models_simple_otoroshi_admin import OtoroshiModelsSimpleOtoroshiAdmin


class TestOtoroshiModelsSimpleOtoroshiAdmin(unittest.TestCase):
    """OtoroshiModelsSimpleOtoroshiAdmin unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOtoroshiModelsSimpleOtoroshiAdmin(self):
        """Test OtoroshiModelsSimpleOtoroshiAdmin"""
        # FIXME: construct object with mandatory attributes with example values
        # model = OtoroshiModelsSimpleOtoroshiAdmin()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
