"""
    Otoroshi Admin API

    Admin API of the Otoroshi reverse proxy  # noqa: E501

    The version of the OpenAPI document: 1.5.0-alpha.14
    Contact: oss@maif.fr
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.otoroshi_models_clever_cloud_settings import OtoroshiModelsCleverCloudSettings


class TestOtoroshiModelsCleverCloudSettings(unittest.TestCase):
    """OtoroshiModelsCleverCloudSettings unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOtoroshiModelsCleverCloudSettings(self):
        """Test OtoroshiModelsCleverCloudSettings"""
        # FIXME: construct object with mandatory attributes with example values
        # model = OtoroshiModelsCleverCloudSettings()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
