"""
    Otoroshi Admin API

    Admin API of the Otoroshi reverse proxy  # noqa: E501

    The version of the OpenAPI document: 1.5.0-alpha.14
    Contact: oss@maif.fr
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.otoroshi_models_hs_algo_settings import OtoroshiModelsHSAlgoSettings


class TestOtoroshiModelsHSAlgoSettings(unittest.TestCase):
    """OtoroshiModelsHSAlgoSettings unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOtoroshiModelsHSAlgoSettings(self):
        """Test OtoroshiModelsHSAlgoSettings"""
        # FIXME: construct object with mandatory attributes with example values
        # model = OtoroshiModelsHSAlgoSettings()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
