"""
    Otoroshi Admin API

    Admin API of the Otoroshi reverse proxy  # noqa: E501

    The version of the OpenAPI document: 1.5.0-alpha.14
    Contact: oss@maif.fr
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.otoroshi_models_target_predicate import OtoroshiModelsTargetPredicate
from openapi_client.model.otoroshi_utils_http_mtls_config import OtoroshiUtilsHttpMtlsConfig
globals()['OtoroshiModelsTargetPredicate'] = OtoroshiModelsTargetPredicate
globals()['OtoroshiUtilsHttpMtlsConfig'] = OtoroshiUtilsHttpMtlsConfig
from openapi_client.model.otoroshi_models_target import OtoroshiModelsTarget


class TestOtoroshiModelsTarget(unittest.TestCase):
    """OtoroshiModelsTarget unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOtoroshiModelsTarget(self):
        """Test OtoroshiModelsTarget"""
        # FIXME: construct object with mandatory attributes with example values
        # model = OtoroshiModelsTarget()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
