"""
    Otoroshi Admin API

    Admin API of the Otoroshi reverse proxy  # noqa: E501

    The version of the OpenAPI document: 1.5.0-alpha.14
    Contact: oss@maif.fr
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.otoroshi_models_algo_settings import OtoroshiModelsAlgoSettings
from openapi_client.model.otoroshi_models_transform_settings import OtoroshiModelsTransformSettings
from openapi_client.model.otoroshi_models_verification_settings import OtoroshiModelsVerificationSettings
globals()['OtoroshiModelsAlgoSettings'] = OtoroshiModelsAlgoSettings
globals()['OtoroshiModelsTransformSettings'] = OtoroshiModelsTransformSettings
globals()['OtoroshiModelsVerificationSettings'] = OtoroshiModelsVerificationSettings
from openapi_client.model.otoroshi_models_transform import OtoroshiModelsTransform


class TestOtoroshiModelsTransform(unittest.TestCase):
    """OtoroshiModelsTransform unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOtoroshiModelsTransform(self):
        """Test OtoroshiModelsTransform"""
        # FIXME: construct object with mandatory attributes with example values
        # model = OtoroshiModelsTransform()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
