"""
    Otoroshi Admin API

    Admin API of the Otoroshi reverse proxy  # noqa: E501

    The version of the OpenAPI document: 1.5.0-alpha.14
    Contact: oss@maif.fr
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.otoroshi_models_es_algo_settings import OtoroshiModelsESAlgoSettings


class TestOtoroshiModelsESAlgoSettings(unittest.TestCase):
    """OtoroshiModelsESAlgoSettings unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOtoroshiModelsESAlgoSettings(self):
        """Test OtoroshiModelsESAlgoSettings"""
        # FIXME: construct object with mandatory attributes with example values
        # model = OtoroshiModelsESAlgoSettings()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
