"""
    Otoroshi Admin API

    Admin API of the Otoroshi reverse proxy  # noqa: E501

    The version of the OpenAPI document: 1.5.0-alpha.14
    Contact: oss@maif.fr
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.otoroshi_events_kafka_config import OtoroshiEventsKafkaConfig
from openapi_client.model.otoroshi_events_pulsar_config import OtoroshiEventsPulsarConfig
from openapi_client.model.otoroshi_models_console_settings import OtoroshiModelsConsoleSettings
from openapi_client.model.otoroshi_models_elastic_analytics_config import OtoroshiModelsElasticAnalyticsConfig
from openapi_client.model.otoroshi_models_exporter_ref import OtoroshiModelsExporterRef
from openapi_client.model.otoroshi_models_file_settings import OtoroshiModelsFileSettings
from openapi_client.model.otoroshi_models_metrics_settings import OtoroshiModelsMetricsSettings
from openapi_client.model.otoroshi_models_webhook import OtoroshiModelsWebhook
from openapi_client.model.otoroshi_utils_http_mtls_config import OtoroshiUtilsHttpMtlsConfig
from openapi_client.model.otoroshi_utils_mailer_console_mailer_settings import OtoroshiUtilsMailerConsoleMailerSettings
from openapi_client.model.otoroshi_utils_mailer_email_location import OtoroshiUtilsMailerEmailLocation
from openapi_client.model.otoroshi_utils_mailer_generic_mailer_settings import OtoroshiUtilsMailerGenericMailerSettings
from openapi_client.model.otoroshi_utils_mailer_mailer_settings import OtoroshiUtilsMailerMailerSettings
from openapi_client.model.otoroshi_utils_mailer_mailgun_settings import OtoroshiUtilsMailerMailgunSettings
from openapi_client.model.otoroshi_utils_mailer_mailjet_settings import OtoroshiUtilsMailerMailjetSettings
from openapi_client.model.otoroshi_utils_mailer_none_mailer_settings import OtoroshiUtilsMailerNoneMailerSettings
from openapi_client.model.otoroshi_utils_mailer_sendgrid_settings import OtoroshiUtilsMailerSendgridSettings
globals()['OtoroshiEventsKafkaConfig'] = OtoroshiEventsKafkaConfig
globals()['OtoroshiEventsPulsarConfig'] = OtoroshiEventsPulsarConfig
globals()['OtoroshiModelsConsoleSettings'] = OtoroshiModelsConsoleSettings
globals()['OtoroshiModelsElasticAnalyticsConfig'] = OtoroshiModelsElasticAnalyticsConfig
globals()['OtoroshiModelsExporterRef'] = OtoroshiModelsExporterRef
globals()['OtoroshiModelsFileSettings'] = OtoroshiModelsFileSettings
globals()['OtoroshiModelsMetricsSettings'] = OtoroshiModelsMetricsSettings
globals()['OtoroshiModelsWebhook'] = OtoroshiModelsWebhook
globals()['OtoroshiUtilsHttpMtlsConfig'] = OtoroshiUtilsHttpMtlsConfig
globals()['OtoroshiUtilsMailerConsoleMailerSettings'] = OtoroshiUtilsMailerConsoleMailerSettings
globals()['OtoroshiUtilsMailerEmailLocation'] = OtoroshiUtilsMailerEmailLocation
globals()['OtoroshiUtilsMailerGenericMailerSettings'] = OtoroshiUtilsMailerGenericMailerSettings
globals()['OtoroshiUtilsMailerMailerSettings'] = OtoroshiUtilsMailerMailerSettings
globals()['OtoroshiUtilsMailerMailgunSettings'] = OtoroshiUtilsMailerMailgunSettings
globals()['OtoroshiUtilsMailerMailjetSettings'] = OtoroshiUtilsMailerMailjetSettings
globals()['OtoroshiUtilsMailerNoneMailerSettings'] = OtoroshiUtilsMailerNoneMailerSettings
globals()['OtoroshiUtilsMailerSendgridSettings'] = OtoroshiUtilsMailerSendgridSettings
from openapi_client.model.otoroshi_models_exporter import OtoroshiModelsExporter


class TestOtoroshiModelsExporter(unittest.TestCase):
    """OtoroshiModelsExporter unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOtoroshiModelsExporter(self):
        """Test OtoroshiModelsExporter"""
        # FIXME: construct object with mandatory attributes with example values
        # model = OtoroshiModelsExporter()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
