"""
    Otoroshi Admin API

    Admin API of the Otoroshi reverse proxy  # noqa: E501

    The version of the OpenAPI document: 1.5.0-alpha.14
    Contact: oss@maif.fr
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.otoroshi_models_rsakp_algo_settings import OtoroshiModelsRSAKPAlgoSettings


class TestOtoroshiModelsRSAKPAlgoSettings(unittest.TestCase):
    """OtoroshiModelsRSAKPAlgoSettings unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOtoroshiModelsRSAKPAlgoSettings(self):
        """Test OtoroshiModelsRSAKPAlgoSettings"""
        # FIXME: construct object with mandatory attributes with example values
        # model = OtoroshiModelsRSAKPAlgoSettings()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
