"""
    Otoroshi Admin API

    Admin API of the Otoroshi reverse proxy  # noqa: E501

    The version of the OpenAPI document: 1.5.0-alpha.14
    Contact: oss@maif.fr
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.otoroshi_utils_mailer_console_mailer_settings import OtoroshiUtilsMailerConsoleMailerSettings
from openapi_client.model.otoroshi_utils_mailer_email_location import OtoroshiUtilsMailerEmailLocation
from openapi_client.model.otoroshi_utils_mailer_generic_mailer_settings import OtoroshiUtilsMailerGenericMailerSettings
from openapi_client.model.otoroshi_utils_mailer_mailgun_settings import OtoroshiUtilsMailerMailgunSettings
from openapi_client.model.otoroshi_utils_mailer_mailjet_settings import OtoroshiUtilsMailerMailjetSettings
from openapi_client.model.otoroshi_utils_mailer_none_mailer_settings import OtoroshiUtilsMailerNoneMailerSettings
from openapi_client.model.otoroshi_utils_mailer_sendgrid_settings import OtoroshiUtilsMailerSendgridSettings
globals()['OtoroshiUtilsMailerConsoleMailerSettings'] = OtoroshiUtilsMailerConsoleMailerSettings
globals()['OtoroshiUtilsMailerEmailLocation'] = OtoroshiUtilsMailerEmailLocation
globals()['OtoroshiUtilsMailerGenericMailerSettings'] = OtoroshiUtilsMailerGenericMailerSettings
globals()['OtoroshiUtilsMailerMailgunSettings'] = OtoroshiUtilsMailerMailgunSettings
globals()['OtoroshiUtilsMailerMailjetSettings'] = OtoroshiUtilsMailerMailjetSettings
globals()['OtoroshiUtilsMailerNoneMailerSettings'] = OtoroshiUtilsMailerNoneMailerSettings
globals()['OtoroshiUtilsMailerSendgridSettings'] = OtoroshiUtilsMailerSendgridSettings
from openapi_client.model.otoroshi_utils_mailer_mailer_settings import OtoroshiUtilsMailerMailerSettings


class TestOtoroshiUtilsMailerMailerSettings(unittest.TestCase):
    """OtoroshiUtilsMailerMailerSettings unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOtoroshiUtilsMailerMailerSettings(self):
        """Test OtoroshiUtilsMailerMailerSettings"""
        # FIXME: construct object with mandatory attributes with example values
        # model = OtoroshiUtilsMailerMailerSettings()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
