"""
    Otoroshi Admin API

    Admin API of the Otoroshi reverse proxy  # noqa: E501

    The version of the OpenAPI document: 1.5.0-alpha.14
    Contact: oss@maif.fr
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from openapi_client.api.privateapps_api import PrivateappsApi  # noqa: E501


class TestPrivateappsApi(unittest.TestCase):
    """PrivateappsApi unit test stubs"""

    def setUp(self):
        self.api = PrivateappsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_otoroshi_controllers_private_apps_controller_register_session(self):
        """Test case for otoroshi_controllers_private_apps_controller_register_session

        Registers a private app session  # noqa: E501
        """
        pass

    def test_otoroshi_controllers_private_apps_controller_send_self_update_link(self):
        """Test case for otoroshi_controllers_private_apps_controller_send_self_update_link

        Send an email to a user to update its own settings  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
