"""
    Otoroshi Admin API

    Admin API of the Otoroshi reverse proxy  # noqa: E501

    The version of the OpenAPI document: 1.5.0-alpha.14
    Contact: oss@maif.fr
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from openapi_client.api.teams_api import TeamsApi  # noqa: E501


class TestTeamsApi(unittest.TestCase):
    """TeamsApi unit test stubs"""

    def setUp(self):
        self.api = TeamsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_otoroshi_controllers_adminapi_teams_controller_bulk_create_action(self):
        """Test case for otoroshi_controllers_adminapi_teams_controller_bulk_create_action

        Create multiple Teams at the same time  # noqa: E501
        """
        pass

    def test_otoroshi_controllers_adminapi_teams_controller_bulk_delete_action(self):
        """Test case for otoroshi_controllers_adminapi_teams_controller_bulk_delete_action

        Delete multiple Teams at the same time  # noqa: E501
        """
        pass

    def test_otoroshi_controllers_adminapi_teams_controller_bulk_patch_action(self):
        """Test case for otoroshi_controllers_adminapi_teams_controller_bulk_patch_action

        Update (using json-patch) multiple Teams at the same time  # noqa: E501
        """
        pass

    def test_otoroshi_controllers_adminapi_teams_controller_bulk_update_action(self):
        """Test case for otoroshi_controllers_adminapi_teams_controller_bulk_update_action

        Update multiple Teams at the same time  # noqa: E501
        """
        pass

    def test_otoroshi_controllers_adminapi_teams_controller_create_action(self):
        """Test case for otoroshi_controllers_adminapi_teams_controller_create_action

        Creates a Team  # noqa: E501
        """
        pass

    def test_otoroshi_controllers_adminapi_teams_controller_delete_entity_action(self):
        """Test case for otoroshi_controllers_adminapi_teams_controller_delete_entity_action

        Deletes a specific Team using its id  # noqa: E501
        """
        pass

    def test_otoroshi_controllers_adminapi_teams_controller_find_all_entities_action(self):
        """Test case for otoroshi_controllers_adminapi_teams_controller_find_all_entities_action

        Find all possible Teams entities  # noqa: E501
        """
        pass

    def test_otoroshi_controllers_adminapi_teams_controller_find_entity_by_id_action(self):
        """Test case for otoroshi_controllers_adminapi_teams_controller_find_entity_by_id_action

        Find a specific Team using its id  # noqa: E501
        """
        pass

    def test_otoroshi_controllers_adminapi_teams_controller_patch_entity_action(self):
        """Test case for otoroshi_controllers_adminapi_teams_controller_patch_entity_action

        Updates (using json-patch) a specific Team using its id  # noqa: E501
        """
        pass

    def test_otoroshi_controllers_adminapi_teams_controller_update_entity_action(self):
        """Test case for otoroshi_controllers_adminapi_teams_controller_update_entity_action

        Updates a specific Team using its id  # noqa: E501
        """
        pass

    def test_otoroshi_controllers_adminapi_templates_controller_initiate_team(self):
        """Test case for otoroshi_controllers_adminapi_templates_controller_initiate_team

        Creates a new Team from a template  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
