"""
    Otoroshi Admin API

    Admin API of the Otoroshi reverse proxy  # noqa: E501

    The version of the OpenAPI document: 1.5.0-alpha.14
    Contact: oss@maif.fr
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.otoroshi_auth_basic_auth_user import OtoroshiAuthBasicAuthUser
from openapi_client.model.otoroshi_auth_session_cookie_values import OtoroshiAuthSessionCookieValues
from openapi_client.model.otoroshi_models_entity_location import OtoroshiModelsEntityLocation
globals()['OtoroshiAuthBasicAuthUser'] = OtoroshiAuthBasicAuthUser
globals()['OtoroshiAuthSessionCookieValues'] = OtoroshiAuthSessionCookieValues
globals()['OtoroshiModelsEntityLocation'] = OtoroshiModelsEntityLocation
from openapi_client.model.otoroshi_auth_basic_auth_module_config import OtoroshiAuthBasicAuthModuleConfig


class TestOtoroshiAuthBasicAuthModuleConfig(unittest.TestCase):
    """OtoroshiAuthBasicAuthModuleConfig unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOtoroshiAuthBasicAuthModuleConfig(self):
        """Test OtoroshiAuthBasicAuthModuleConfig"""
        # FIXME: construct object with mandatory attributes with example values
        # model = OtoroshiAuthBasicAuthModuleConfig()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
