"""
    Otoroshi Admin API

    Admin API of the Otoroshi reverse proxy  # noqa: E501

    The version of the OpenAPI document: 1.5.0-alpha.14
    Contact: oss@maif.fr
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.otoroshi_events_health_check_event import OtoroshiEventsHealthCheckEvent
globals()['OtoroshiEventsHealthCheckEvent'] = OtoroshiEventsHealthCheckEvent
from openapi_client.model.health_check_event_list import HealthCheckEventList


class TestHealthCheckEventList(unittest.TestCase):
    """HealthCheckEventList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testHealthCheckEventList(self):
        """Test HealthCheckEventList"""
        # FIXME: construct object with mandatory attributes with example values
        # model = HealthCheckEventList()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
