"""
    Otoroshi Admin API

    Admin API of the Otoroshi reverse proxy  # noqa: E501

    The version of the OpenAPI document: 1.5.0-alpha.14
    Contact: oss@maif.fr
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from openapi_client.api.snowmonkey_api import SnowmonkeyApi  # noqa: E501


class TestSnowmonkeyApi(unittest.TestCase):
    """SnowmonkeyApi unit test stubs"""

    def setUp(self):
        self.api = SnowmonkeyApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_otoroshi_controllers_adminapi_snow_monkey_controller_get_snow_monkey_config(self):
        """Test case for otoroshi_controllers_adminapi_snow_monkey_controller_get_snow_monkey_config

        Get the snowmonkey config  # noqa: E501
        """
        pass

    def test_otoroshi_controllers_adminapi_snow_monkey_controller_get_snow_monkey_outages(self):
        """Test case for otoroshi_controllers_adminapi_snow_monkey_controller_get_snow_monkey_outages

        Get the current snowmonkey outages  # noqa: E501
        """
        pass

    def test_otoroshi_controllers_adminapi_snow_monkey_controller_patch_snow_monkey(self):
        """Test case for otoroshi_controllers_adminapi_snow_monkey_controller_patch_snow_monkey

        Updates (using json-patch) the snowmonkey configuration  # noqa: E501
        """
        pass

    def test_otoroshi_controllers_adminapi_snow_monkey_controller_reset_snow_monkey(self):
        """Test case for otoroshi_controllers_adminapi_snow_monkey_controller_reset_snow_monkey

        Reset the snowmonkey outages  # noqa: E501
        """
        pass

    def test_otoroshi_controllers_adminapi_snow_monkey_controller_start_snow_monkey(self):
        """Test case for otoroshi_controllers_adminapi_snow_monkey_controller_start_snow_monkey

        Start the snowmonkey of all otoroshi instances  # noqa: E501
        """
        pass

    def test_otoroshi_controllers_adminapi_snow_monkey_controller_stop_snow_monkey(self):
        """Test case for otoroshi_controllers_adminapi_snow_monkey_controller_stop_snow_monkey

        Stop the snowmonkey of all otoroshi instances  # noqa: E501
        """
        pass

    def test_otoroshi_controllers_adminapi_snow_monkey_controller_update_snow_monkey(self):
        """Test case for otoroshi_controllers_adminapi_snow_monkey_controller_update_snow_monkey

        Updates the snowmonkey configuration  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
