"""
    Otoroshi Admin API

    Admin API of the Otoroshi reverse proxy  # noqa: E501

    The version of the OpenAPI document: 1.5.0-alpha.14
    Contact: oss@maif.fr
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from openapi_client.api.apps_sessions_api import AppsSessionsApi  # noqa: E501


class TestAppsSessionsApi(unittest.TestCase):
    """AppsSessionsApi unit test stubs"""

    def setUp(self):
        self.api = AppsSessionsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_otoroshi_controllers_adminapi_users_controller_discard_all_private_apps_sessions(self):
        """Test case for otoroshi_controllers_adminapi_users_controller_discard_all_private_apps_sessions

        Discard all private apps sessions  # noqa: E501
        """
        pass

    def test_otoroshi_controllers_adminapi_users_controller_discard_private_apps_session(self):
        """Test case for otoroshi_controllers_adminapi_users_controller_discard_private_apps_session

        Discard a specific private apps session  # noqa: E501
        """
        pass

    def test_otoroshi_controllers_adminapi_users_controller_private_apps_sessions(self):
        """Test case for otoroshi_controllers_adminapi_users_controller_private_apps_sessions

        Return all private apps sessions  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
