"""
    Otoroshi Admin API

    Admin API of the Otoroshi reverse proxy  # noqa: E501

    The version of the OpenAPI document: 1.5.0-alpha.14
    Contact: oss@maif.fr
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.otoroshi_models_algo_settings import OtoroshiModelsAlgoSettings
from openapi_client.model.otoroshi_models_jwt_token_location import OtoroshiModelsJwtTokenLocation
from openapi_client.model.otoroshi_models_verifier_strategy import OtoroshiModelsVerifierStrategy
globals()['OtoroshiModelsAlgoSettings'] = OtoroshiModelsAlgoSettings
globals()['OtoroshiModelsJwtTokenLocation'] = OtoroshiModelsJwtTokenLocation
globals()['OtoroshiModelsVerifierStrategy'] = OtoroshiModelsVerifierStrategy
from openapi_client.model.otoroshi_models_local_jwt_verifier import OtoroshiModelsLocalJwtVerifier


class TestOtoroshiModelsLocalJwtVerifier(unittest.TestCase):
    """OtoroshiModelsLocalJwtVerifier unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOtoroshiModelsLocalJwtVerifier(self):
        """Test OtoroshiModelsLocalJwtVerifier"""
        # FIXME: construct object with mandatory attributes with example values
        # model = OtoroshiModelsLocalJwtVerifier()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
