"""
    Otoroshi Admin API

    Admin API of the Otoroshi reverse proxy  # noqa: E501

    The version of the OpenAPI document: 1.5.0-alpha.14
    Contact: oss@maif.fr
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.otoroshi_ssl_pki_models_gen_key_pair_response import OtoroshiSslPkiModelsGenKeyPairResponse


class TestOtoroshiSslPkiModelsGenKeyPairResponse(unittest.TestCase):
    """OtoroshiSslPkiModelsGenKeyPairResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOtoroshiSslPkiModelsGenKeyPairResponse(self):
        """Test OtoroshiSslPkiModelsGenKeyPairResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = OtoroshiSslPkiModelsGenKeyPairResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
