"""
    Otoroshi Admin API

    Admin API of the Otoroshi reverse proxy  # noqa: E501

    The version of the OpenAPI document: 1.5.0-alpha.14
    Contact: oss@maif.fr
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from openapi_client.api.admins_api import AdminsApi  # noqa: E501


class TestAdminsApi(unittest.TestCase):
    """AdminsApi unit test stubs"""

    def setUp(self):
        self.api = AdminsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_otoroshi_controllers_adminapi_templates_controller_create_from_template_simple(self):
        """Test case for otoroshi_controllers_adminapi_templates_controller_create_from_template_simple

        Creates a new Template from a template  # noqa: E501
        """
        pass

    def test_otoroshi_controllers_adminapi_templates_controller_create_from_template_webauthn(self):
        """Test case for otoroshi_controllers_adminapi_templates_controller_create_from_template_webauthn

        Creates a new Template from a template  # noqa: E501
        """
        pass

    def test_otoroshi_controllers_adminapi_templates_controller_initiate_simple_admin(self):
        """Test case for otoroshi_controllers_adminapi_templates_controller_initiate_simple_admin

        Creates a new SimpleAdmin from a template  # noqa: E501
        """
        pass

    def test_otoroshi_controllers_adminapi_templates_controller_initiate_webauthn_admin(self):
        """Test case for otoroshi_controllers_adminapi_templates_controller_initiate_webauthn_admin

        Creates a new WebauthnAdmin from a template  # noqa: E501
        """
        pass

    def test_otoroshi_controllers_adminapi_users_controller_delete_admin(self):
        """Test case for otoroshi_controllers_adminapi_users_controller_delete_admin

        Deletes an admin  # noqa: E501
        """
        pass

    def test_otoroshi_controllers_adminapi_users_controller_register_simple_admin(self):
        """Test case for otoroshi_controllers_adminapi_users_controller_register_simple_admin

        Register an admin user  # noqa: E501
        """
        pass

    def test_otoroshi_controllers_adminapi_users_controller_register_web_authn_admin(self):
        """Test case for otoroshi_controllers_adminapi_users_controller_register_web_authn_admin

        Register a webauthn admin user  # noqa: E501
        """
        pass

    def test_otoroshi_controllers_adminapi_users_controller_simple_admins(self):
        """Test case for otoroshi_controllers_adminapi_users_controller_simple_admins

        Returns all admins  # noqa: E501
        """
        pass

    def test_otoroshi_controllers_adminapi_users_controller_update_admin(self):
        """Test case for otoroshi_controllers_adminapi_users_controller_update_admin

        Updates an admin  # noqa: E501
        """
        pass

    def test_otoroshi_controllers_adminapi_users_controller_update_web_authn_admin(self):
        """Test case for otoroshi_controllers_adminapi_users_controller_update_web_authn_admin

        Updates a webauthn admin  # noqa: E501
        """
        pass

    def test_otoroshi_controllers_adminapi_users_controller_web_authn_admins(self):
        """Test case for otoroshi_controllers_adminapi_users_controller_web_authn_admins

        Returns all webauthn admin  # noqa: E501
        """
        pass

    def test_otoroshi_controllers_adminapi_users_controller_web_authn_delete_admin(self):
        """Test case for otoroshi_controllers_adminapi_users_controller_web_authn_delete_admin

        Deletes a webauthn admin  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
