"""
    Otoroshi Admin API

    Admin API of the Otoroshi reverse proxy  # noqa: E501

    The version of the OpenAPI document: 1.5.0-alpha.14
    Contact: oss@maif.fr
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.otoroshi_models_jwt_token_location import OtoroshiModelsJwtTokenLocation
from openapi_client.model.otoroshi_models_mapping_settings import OtoroshiModelsMappingSettings
globals()['OtoroshiModelsJwtTokenLocation'] = OtoroshiModelsJwtTokenLocation
globals()['OtoroshiModelsMappingSettings'] = OtoroshiModelsMappingSettings
from openapi_client.model.otoroshi_models_transform_settings import OtoroshiModelsTransformSettings


class TestOtoroshiModelsTransformSettings(unittest.TestCase):
    """OtoroshiModelsTransformSettings unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOtoroshiModelsTransformSettings(self):
        """Test OtoroshiModelsTransformSettings"""
        # FIXME: construct object with mandatory attributes with example values
        # model = OtoroshiModelsTransformSettings()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
