"""
    Otoroshi Admin API

    Admin API of the Otoroshi reverse proxy  # noqa: E501

    The version of the OpenAPI document: 1.5.0-alpha.14
    Contact: oss@maif.fr
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.otoroshi_utils_mailer_email_location import OtoroshiUtilsMailerEmailLocation
globals()['OtoroshiUtilsMailerEmailLocation'] = OtoroshiUtilsMailerEmailLocation
from openapi_client.model.otoroshi_utils_mailer_sendgrid_settings import OtoroshiUtilsMailerSendgridSettings


class TestOtoroshiUtilsMailerSendgridSettings(unittest.TestCase):
    """OtoroshiUtilsMailerSendgridSettings unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOtoroshiUtilsMailerSendgridSettings(self):
        """Test OtoroshiUtilsMailerSendgridSettings"""
        # FIXME: construct object with mandatory attributes with example values
        # model = OtoroshiUtilsMailerSendgridSettings()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
