"""
    Otoroshi Admin API

    Admin API of the Otoroshi reverse proxy  # noqa: E501

    The version of the OpenAPI document: 1.5.0-alpha.14
    Contact: oss@maif.fr
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.otoroshi_models_entity_location import OtoroshiModelsEntityLocation
from openapi_client.model.otoroshi_models_user_rights import OtoroshiModelsUserRights
globals()['OtoroshiModelsEntityLocation'] = OtoroshiModelsEntityLocation
globals()['OtoroshiModelsUserRights'] = OtoroshiModelsUserRights
from openapi_client.model.otoroshi_models_back_office_user import OtoroshiModelsBackOfficeUser


class TestOtoroshiModelsBackOfficeUser(unittest.TestCase):
    """OtoroshiModelsBackOfficeUser unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOtoroshiModelsBackOfficeUser(self):
        """Test OtoroshiModelsBackOfficeUser"""
        # FIXME: construct object with mandatory attributes with example values
        # model = OtoroshiModelsBackOfficeUser()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
