"""
    Otoroshi Admin API

    Admin API of the Otoroshi reverse proxy  # noqa: E501

    The version of the OpenAPI document: 1.5.0-alpha.14
    Contact: oss@maif.fr
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from openapi_client.api.organizations_api import OrganizationsApi  # noqa: E501


class TestOrganizationsApi(unittest.TestCase):
    """OrganizationsApi unit test stubs"""

    def setUp(self):
        self.api = OrganizationsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_otoroshi_controllers_adminapi_templates_controller_initiate_tenant(self):
        """Test case for otoroshi_controllers_adminapi_templates_controller_initiate_tenant

        Creates a new Tenant from a template  # noqa: E501
        """
        pass

    def test_otoroshi_controllers_adminapi_tenants_controller_bulk_create_action(self):
        """Test case for otoroshi_controllers_adminapi_tenants_controller_bulk_create_action

        Create multiple Tenants at the same time  # noqa: E501
        """
        pass

    def test_otoroshi_controllers_adminapi_tenants_controller_bulk_delete_action(self):
        """Test case for otoroshi_controllers_adminapi_tenants_controller_bulk_delete_action

        Delete multiple Tenants at the same time  # noqa: E501
        """
        pass

    def test_otoroshi_controllers_adminapi_tenants_controller_bulk_patch_action(self):
        """Test case for otoroshi_controllers_adminapi_tenants_controller_bulk_patch_action

        Update (using json-patch) multiple Tenants at the same time  # noqa: E501
        """
        pass

    def test_otoroshi_controllers_adminapi_tenants_controller_bulk_update_action(self):
        """Test case for otoroshi_controllers_adminapi_tenants_controller_bulk_update_action

        Update multiple Tenants at the same time  # noqa: E501
        """
        pass

    def test_otoroshi_controllers_adminapi_tenants_controller_create_action(self):
        """Test case for otoroshi_controllers_adminapi_tenants_controller_create_action

        Creates a Tenant  # noqa: E501
        """
        pass

    def test_otoroshi_controllers_adminapi_tenants_controller_delete_entity_action(self):
        """Test case for otoroshi_controllers_adminapi_tenants_controller_delete_entity_action

        Deletes a specific Tenant using its id  # noqa: E501
        """
        pass

    def test_otoroshi_controllers_adminapi_tenants_controller_find_all_entities_action(self):
        """Test case for otoroshi_controllers_adminapi_tenants_controller_find_all_entities_action

        Find all possible Tenants entities  # noqa: E501
        """
        pass

    def test_otoroshi_controllers_adminapi_tenants_controller_find_entity_by_id_action(self):
        """Test case for otoroshi_controllers_adminapi_tenants_controller_find_entity_by_id_action

        Find a specific Tenant using its id  # noqa: E501
        """
        pass

    def test_otoroshi_controllers_adminapi_tenants_controller_patch_entity_action(self):
        """Test case for otoroshi_controllers_adminapi_tenants_controller_patch_entity_action

        Updates (using json-patch) a specific Tenant using its id  # noqa: E501
        """
        pass

    def test_otoroshi_controllers_adminapi_tenants_controller_update_entity_action(self):
        """Test case for otoroshi_controllers_adminapi_tenants_controller_update_entity_action

        Updates a specific Tenant using its id  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
