"""
    Otoroshi Admin API

    Admin API of the Otoroshi reverse proxy  # noqa: E501

    The version of the OpenAPI document: 1.5.0-alpha.14
    Contact: oss@maif.fr
    Generated by: https://openapi-generator.tech
"""


import re  # noqa: F401
import sys  # noqa: F401

from openapi_client.model_utils import (  # noqa: F401
    ApiTypeError,
    ModelComposed,
    ModelNormal,
    ModelSimple,
    cached_property,
    change_keys_js_to_python,
    convert_js_args_to_python_args,
    date,
    datetime,
    file_type,
    none_type,
    validate_get_composed_info,
)
from ..model_utils import OpenApiModel
from openapi_client.exceptions import ApiAttributeError


def lazy_import():
    from openapi_client.model.otoroshi_auth_group_filter import OtoroshiAuthGroupFilter
    from openapi_client.model.otoroshi_auth_group_rights import OtoroshiAuthGroupRights
    from openapi_client.model.otoroshi_auth_session_cookie_values import OtoroshiAuthSessionCookieValues
    from openapi_client.model.otoroshi_models_entity_location import OtoroshiModelsEntityLocation
    from openapi_client.model.otoroshi_models_user_rights import OtoroshiModelsUserRights
    globals()['OtoroshiAuthGroupFilter'] = OtoroshiAuthGroupFilter
    globals()['OtoroshiAuthGroupRights'] = OtoroshiAuthGroupRights
    globals()['OtoroshiAuthSessionCookieValues'] = OtoroshiAuthSessionCookieValues
    globals()['OtoroshiModelsEntityLocation'] = OtoroshiModelsEntityLocation
    globals()['OtoroshiModelsUserRights'] = OtoroshiModelsUserRights


class OtoroshiAuthLdapAuthModuleConfig(ModelNormal):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.

    Attributes:
      allowed_values (dict): The key is the tuple path to the attribute
          and the for var_name this is (var_name,). The value is a dict
          with a capitalized key describing the allowed value and an allowed
          value. These dicts store the allowed enum values.
      attribute_map (dict): The key is attribute name
          and the value is json key in definition.
      discriminator_value_class_map (dict): A dict to go from the discriminator
          variable value to the discriminator class name.
      validations (dict): The key is the tuple path to the attribute
          and the for var_name this is (var_name,). The value is a dict
          that stores validations for max_length, min_length, max_items,
          min_items, exclusive_maximum, inclusive_maximum, exclusive_minimum,
          inclusive_minimum, and regex.
      additional_properties_type (tuple): A tuple of classes accepted
          as additional properties values.
    """

    allowed_values = {
        ('type',): {
            'SAML': "saml",
            'OAUTH1': "oauth1",
            'OAUTH2': "oauth2",
            'LDAP': "ldap",
            'BASIC': "basic",
        },
    }

    validations = {
    }

    @cached_property
    def additional_properties_type():
        """
        This must be a method because a model may have properties that are
        of type self, this must run after the class is loaded
        """
        lazy_import()
        return (bool, date, datetime, dict, float, int, list, str, none_type,)  # noqa: E501

    _nullable = False

    @cached_property
    def openapi_types():
        """
        This must be a method because a model may have properties that are
        of type self, this must run after the class is loaded

        Returns
            openapi_types (dict): The key is attribute name
                and the value is attribute type.
        """
        lazy_import()
        return {
            'group_filters': ([OtoroshiAuthGroupFilter],),  # noqa: E501
            'metadata': ({str: (str,)},),  # noqa: E501
            'allow_empty_password': (bool,),  # noqa: E501
            'basic_auth': (bool,),  # noqa: E501
            'search_base': (str,),  # noqa: E501
            'name_field': (str,),  # noqa: E501
            'email_field': (str,),  # noqa: E501
            'type': (str,),  # noqa: E501
            'metadata_field': (dict,),  # noqa: E501
            'rights_override': ({str: (OtoroshiModelsUserRights,)},),  # noqa: E501
            'group_rights': ({str: (OtoroshiAuthGroupRights,)},),  # noqa: E501
            'id': (str,),  # noqa: E501
            'extra_metadata': ({str: (bool, date, datetime, dict, float, int, list, str, none_type)},),  # noqa: E501
            'search_filter': (str,),  # noqa: E501
            'admin_password': (dict,),  # noqa: E501
            'session_cookie_values': (OtoroshiAuthSessionCookieValues,),  # noqa: E501
            'data_override': ({str: ({str: (bool, date, datetime, dict, float, int, list, str, none_type)},)},),  # noqa: E501
            'super_admins': (bool,),  # noqa: E501
            'user_base': (dict,),  # noqa: E501
            'server_urls': ([str],),  # noqa: E501
            'tags': ([str],),  # noqa: E501
            'session_max_age': (int,),  # noqa: E501
            'admin_username': (dict,),  # noqa: E501
            'name': (str,),  # noqa: E501
            'location': (OtoroshiModelsEntityLocation,),  # noqa: E501
            'desc': (str,),  # noqa: E501
        }

    @cached_property
    def discriminator():
        return None


    attribute_map = {
        'group_filters': 'groupFilters',  # noqa: E501
        'metadata': 'metadata',  # noqa: E501
        'allow_empty_password': 'allowEmptyPassword',  # noqa: E501
        'basic_auth': 'basicAuth',  # noqa: E501
        'search_base': 'searchBase',  # noqa: E501
        'name_field': 'nameField',  # noqa: E501
        'email_field': 'emailField',  # noqa: E501
        'type': 'type',  # noqa: E501
        'metadata_field': 'metadataField',  # noqa: E501
        'rights_override': 'rightsOverride',  # noqa: E501
        'group_rights': 'groupRights',  # noqa: E501
        'id': 'id',  # noqa: E501
        'extra_metadata': 'extraMetadata',  # noqa: E501
        'search_filter': 'searchFilter',  # noqa: E501
        'admin_password': 'adminPassword',  # noqa: E501
        'session_cookie_values': 'sessionCookieValues',  # noqa: E501
        'data_override': 'dataOverride',  # noqa: E501
        'super_admins': 'superAdmins',  # noqa: E501
        'user_base': 'userBase',  # noqa: E501
        'server_urls': 'serverUrls',  # noqa: E501
        'tags': 'tags',  # noqa: E501
        'session_max_age': 'sessionMaxAge',  # noqa: E501
        'admin_username': 'adminUsername',  # noqa: E501
        'name': 'name',  # noqa: E501
        'location': 'location',  # noqa: E501
        'desc': 'desc',  # noqa: E501
    }

    read_only_vars = {
    }

    _composed_schemas = {}

    @classmethod
    @convert_js_args_to_python_args
    def _from_openapi_data(cls, *args, **kwargs):  # noqa: E501
        """OtoroshiAuthLdapAuthModuleConfig - a model defined in OpenAPI

        Keyword Args:
            _check_type (bool): if True, values for parameters in openapi_types
                                will be type checked and a TypeError will be
                                raised if the wrong type is input.
                                Defaults to True
            _path_to_item (tuple/list): This is a list of keys or values to
                                drill down to the model in received_data
                                when deserializing a response
            _spec_property_naming (bool): True if the variable names in the input data
                                are serialized names, as specified in the OpenAPI document.
                                False if the variable names in the input data
                                are pythonic names, e.g. snake case (default)
            _configuration (Configuration): the instance to use when
                                deserializing a file_type parameter.
                                If passed, type conversion is attempted
                                If omitted no type conversion is done.
            _visited_composed_classes (tuple): This stores a tuple of
                                classes that we have traveled through so that
                                if we see that class again we will not use its
                                discriminator again.
                                When traveling through a discriminator, the
                                composed schema that is
                                is traveled through is added to this set.
                                For example if Animal has a discriminator
                                petType and we pass in "Dog", and the class Dog
                                allOf includes Animal, we move through Animal
                                once using the discriminator, and pick Dog.
                                Then in Dog, we will make an instance of the
                                Animal class but this time we won't travel
                                through its discriminator because we passed in
                                _visited_composed_classes = (Animal,)
            group_filters ([OtoroshiAuthGroupFilter]): LDAP group filters. [optional]  # noqa: E501
            metadata ({str: (str,)}): Metadata of the module. [optional]  # noqa: E501
            allow_empty_password (bool): Allow empty password access. [optional]  # noqa: E501
            basic_auth (bool): Use standard basic auth or web login form. [optional]  # noqa: E501
            search_base (str): LDAP search base. [optional]  # noqa: E501
            name_field (str): Field name to get name from user profile. [optional]  # noqa: E501
            email_field (str): Field name to get email from user profile. [optional]  # noqa: E501
            type (str): the type of the module. [optional]  # noqa: E501
            metadata_field (dict): Field name to get metadata from user profile. [optional]  # noqa: E501
            rights_override ({str: (OtoroshiModelsUserRights,)}): Overrides user rights. Object with email as key. [optional]  # noqa: E501
            group_rights ({str: (OtoroshiAuthGroupRights,)}): Rights associated with groups. [optional]  # noqa: E501
            id (str): Unique id of the config. [optional]  # noqa: E501
            extra_metadata ({str: (bool, date, datetime, dict, float, int, list, str, none_type)}): Add metadata to user. Object with email as key. [optional]  # noqa: E501
            search_filter (str): Filter for users. [optional]  # noqa: E501
            admin_password (dict): The admin password. [optional]  # noqa: E501
            session_cookie_values (OtoroshiAuthSessionCookieValues): [optional]  # noqa: E501
            data_override ({str: ({str: (bool, date, datetime, dict, float, int, list, str, none_type)},)}): Overiddes user data. Object with email as key. [optional]  # noqa: E501
            super_admins (bool): This module produces only super admins. [optional]  # noqa: E501
            user_base (dict): LDAP user base DN. [optional]  # noqa: E501
            server_urls ([str]): LDAP server list of url. [optional]  # noqa: E501
            tags ([str]): Entity tags. [optional]  # noqa: E501
            session_max_age (int): Max age of the session. [optional]  # noqa: E501
            admin_username (dict): The admin username. [optional]  # noqa: E501
            name (str): Name of the config. [optional]  # noqa: E501
            location (OtoroshiModelsEntityLocation): [optional]  # noqa: E501
            desc (str): Description of the config. [optional]  # noqa: E501
        """

        _check_type = kwargs.pop('_check_type', True)
        _spec_property_naming = kwargs.pop('_spec_property_naming', False)
        _path_to_item = kwargs.pop('_path_to_item', ())
        _configuration = kwargs.pop('_configuration', None)
        _visited_composed_classes = kwargs.pop('_visited_composed_classes', ())

        self = super(OpenApiModel, cls).__new__(cls)

        if args:
            raise ApiTypeError(
                "Invalid positional arguments=%s passed to %s. Remove those invalid positional arguments." % (
                    args,
                    self.__class__.__name__,
                ),
                path_to_item=_path_to_item,
                valid_classes=(self.__class__,),
            )

        self._data_store = {}
        self._check_type = _check_type
        self._spec_property_naming = _spec_property_naming
        self._path_to_item = _path_to_item
        self._configuration = _configuration
        self._visited_composed_classes = _visited_composed_classes + (self.__class__,)

        for var_name, var_value in kwargs.items():
            if var_name not in self.attribute_map and \
                        self._configuration is not None and \
                        self._configuration.discard_unknown_keys and \
                        self.additional_properties_type is None:
                # discard variable.
                continue
            setattr(self, var_name, var_value)
        return self

    required_properties = set([
        '_data_store',
        '_check_type',
        '_spec_property_naming',
        '_path_to_item',
        '_configuration',
        '_visited_composed_classes',
    ])

    @convert_js_args_to_python_args
    def __init__(self, *args, **kwargs):  # noqa: E501
        """OtoroshiAuthLdapAuthModuleConfig - a model defined in OpenAPI

        Keyword Args:
            _check_type (bool): if True, values for parameters in openapi_types
                                will be type checked and a TypeError will be
                                raised if the wrong type is input.
                                Defaults to True
            _path_to_item (tuple/list): This is a list of keys or values to
                                drill down to the model in received_data
                                when deserializing a response
            _spec_property_naming (bool): True if the variable names in the input data
                                are serialized names, as specified in the OpenAPI document.
                                False if the variable names in the input data
                                are pythonic names, e.g. snake case (default)
            _configuration (Configuration): the instance to use when
                                deserializing a file_type parameter.
                                If passed, type conversion is attempted
                                If omitted no type conversion is done.
            _visited_composed_classes (tuple): This stores a tuple of
                                classes that we have traveled through so that
                                if we see that class again we will not use its
                                discriminator again.
                                When traveling through a discriminator, the
                                composed schema that is
                                is traveled through is added to this set.
                                For example if Animal has a discriminator
                                petType and we pass in "Dog", and the class Dog
                                allOf includes Animal, we move through Animal
                                once using the discriminator, and pick Dog.
                                Then in Dog, we will make an instance of the
                                Animal class but this time we won't travel
                                through its discriminator because we passed in
                                _visited_composed_classes = (Animal,)
            group_filters ([OtoroshiAuthGroupFilter]): LDAP group filters. [optional]  # noqa: E501
            metadata ({str: (str,)}): Metadata of the module. [optional]  # noqa: E501
            allow_empty_password (bool): Allow empty password access. [optional]  # noqa: E501
            basic_auth (bool): Use standard basic auth or web login form. [optional]  # noqa: E501
            search_base (str): LDAP search base. [optional]  # noqa: E501
            name_field (str): Field name to get name from user profile. [optional]  # noqa: E501
            email_field (str): Field name to get email from user profile. [optional]  # noqa: E501
            type (str): the type of the module. [optional]  # noqa: E501
            metadata_field (dict): Field name to get metadata from user profile. [optional]  # noqa: E501
            rights_override ({str: (OtoroshiModelsUserRights,)}): Overrides user rights. Object with email as key. [optional]  # noqa: E501
            group_rights ({str: (OtoroshiAuthGroupRights,)}): Rights associated with groups. [optional]  # noqa: E501
            id (str): Unique id of the config. [optional]  # noqa: E501
            extra_metadata ({str: (bool, date, datetime, dict, float, int, list, str, none_type)}): Add metadata to user. Object with email as key. [optional]  # noqa: E501
            search_filter (str): Filter for users. [optional]  # noqa: E501
            admin_password (dict): The admin password. [optional]  # noqa: E501
            session_cookie_values (OtoroshiAuthSessionCookieValues): [optional]  # noqa: E501
            data_override ({str: ({str: (bool, date, datetime, dict, float, int, list, str, none_type)},)}): Overiddes user data. Object with email as key. [optional]  # noqa: E501
            super_admins (bool): This module produces only super admins. [optional]  # noqa: E501
            user_base (dict): LDAP user base DN. [optional]  # noqa: E501
            server_urls ([str]): LDAP server list of url. [optional]  # noqa: E501
            tags ([str]): Entity tags. [optional]  # noqa: E501
            session_max_age (int): Max age of the session. [optional]  # noqa: E501
            admin_username (dict): The admin username. [optional]  # noqa: E501
            name (str): Name of the config. [optional]  # noqa: E501
            location (OtoroshiModelsEntityLocation): [optional]  # noqa: E501
            desc (str): Description of the config. [optional]  # noqa: E501
        """

        _check_type = kwargs.pop('_check_type', True)
        _spec_property_naming = kwargs.pop('_spec_property_naming', False)
        _path_to_item = kwargs.pop('_path_to_item', ())
        _configuration = kwargs.pop('_configuration', None)
        _visited_composed_classes = kwargs.pop('_visited_composed_classes', ())

        if args:
            raise ApiTypeError(
                "Invalid positional arguments=%s passed to %s. Remove those invalid positional arguments." % (
                    args,
                    self.__class__.__name__,
                ),
                path_to_item=_path_to_item,
                valid_classes=(self.__class__,),
            )

        self._data_store = {}
        self._check_type = _check_type
        self._spec_property_naming = _spec_property_naming
        self._path_to_item = _path_to_item
        self._configuration = _configuration
        self._visited_composed_classes = _visited_composed_classes + (self.__class__,)

        for var_name, var_value in kwargs.items():
            if var_name not in self.attribute_map and \
                        self._configuration is not None and \
                        self._configuration.discard_unknown_keys and \
                        self.additional_properties_type is None:
                # discard variable.
                continue
            setattr(self, var_name, var_value)
            if var_name in self.read_only_vars:
                raise ApiAttributeError(f"`{var_name}` is a read-only attribute. Use `from_openapi_data` to instantiate "
                                     f"class with read only attributes.")
